# 项目配置
application:
  # 项目名称
  name: KTP

  # 上传文件的路径
  profile: /Users/zhenwen/MyProjects/ClassPle-Vue/classple/file

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 150MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookcrossing?serverTimeZone=UTC+8&useUnicode=true&characterEncoding=utf8
    username: root
    password: zzw12345

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s

server:
  port: 8080

mybatis:
  type-aliases-package: priv.zhenwen.bookcrossing.project.entity
  mapper-locations: classpath*:mapper/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30